In [2]:
import polars as pl

In [14]:
COLUMNS_TO_KEEP = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime",
    "PULocationID",
    "trip_distance",
    "passenger_count",
    "fare_amount",
    "total_amount",
]

In [34]:


df = pl.read_parquet(
    "../data/raw/yellow_tripdata_2025-01.parquet",columns=COLUMNS_TO_KEEP
)
df.describe()

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ tpep_picku ┆ tpep_dropo ┆ PULocatio ┆ trip_dist ┆ passenger ┆ fare_amou ┆ total_amo │
│ ---        ┆ p_datetime ┆ ff_datetim ┆ nID       ┆ ance      ┆ _count    ┆ nt        ┆ unt       │
│ str        ┆ ---        ┆ e          ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆ str        ┆ ---        ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
│            ┆            ┆ str        ┆           ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 3475226    ┆ 3475226    ┆ 3.475226e ┆ 3.475226e ┆ 2.935077e ┆ 3.475226e ┆ 3.475226e │
│            ┆            ┆            ┆ 6         ┆ 6         ┆ 6         ┆ 6         ┆ 6         │
│ null_count ┆ 0          ┆ 0          ┆ 0.0       ┆ 0.0       ┆ 540149.0  ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 2025-01-17 ┆ 2025-01-17 ┆ 165.19157 ┆ 5.855126  ┆ 1.297859  ┆ 17.081803 ┆ 25.611292 │
│            ┆ 11:02:55.9 ┆ 11:17:56.9 ┆ 6         ┆           ┆           ┆           ┆           │
│            ┆ 10964      ┆ 97901      ┆           ┆           ┆           ┆           ┆           │
│ std        ┆ null       ┆ null       ┆ 64.529483 ┆ 564.6016  ┆ 0.75075   ┆ 463.47291 ┆ 463.65847 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 8         ┆ 8         │
│ min        ┆ 2024-12-31 ┆ 2024-12-18 ┆ 1.0       ┆ 0.0       ┆ 0.0       ┆ -900.0    ┆ -901.0    │
│            ┆ 20:47:55   ┆ 07:52:40   ┆           ┆           ┆           ┆           ┆           │
│ 25%        ┆ 2025-01-10 ┆ 2025-01-10 ┆ 132.0     ┆ 0.98      ┆ 1.0       ┆ 8.6       ┆ 15.2      │
│            ┆ 07:59:01   ┆ 08:15:29   ┆           ┆           ┆           ┆           ┆           │
│ 50%        ┆ 2025-01-17 ┆ 2025-01-17 ┆ 162.0     ┆ 1.67      ┆ 1.0       ┆ 12.11     ┆ 19.95     │
│            ┆ 15:41:34   ┆ 15:59:34   ┆           ┆           ┆           ┆           ┆           │
│ 75%        ┆ 2025-01-24 ┆ 2025-01-24 ┆ 234.0     ┆ 3.1       ┆ 1.0       ┆ 19.5      ┆ 27.78     │
│            ┆ 19:34:06   ┆ 19:48:31   ┆           ┆           ┆           ┆           ┆           │
│ max        ┆ 2025-02-01 ┆ 2025-02-01 ┆ 265.0     ┆ 276423.57 ┆ 9.0       ┆ 863372.12 ┆ 863380.37 │
│            ┆ 00:00:44   ┆ 23:44:11   ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [35]:
df.shape

(3475226, 7)

In [36]:
df=df.rename({"tpep_pickup_datetime":"pickup_dt","tpep_dropoff_datetime":"dropoff_dt"})

In [37]:
df.head()

shape: (5, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ pickup_dt    ┆ dropoff_dt  ┆ PULocationI ┆ trip_distan ┆ passenger_c ┆ fare_amount ┆ total_amoun │
│ ---          ┆ ---         ┆ D           ┆ ce          ┆ ount        ┆ ---         ┆ t           │
│ datetime[μs] ┆ datetime[μs ┆ ---         ┆ ---         ┆ ---         ┆ f64         ┆ ---         │
│              ┆ ]           ┆ i32         ┆ f64         ┆ i64         ┆             ┆ f64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 2025-01-01   ┆ 2025-01-01  ┆ 229         ┆ 1.6         ┆ 1           ┆ 10.0        ┆ 18.0        │
│ 00:18:38     ┆ 00:26:59    ┆             ┆             ┆             ┆             ┆             │
│ 2025-01-01   ┆ 2025-01-01  ┆ 236         ┆ 0.5         ┆ 1           ┆ 5.1         ┆ 12.12       │
│ 00:32:40     ┆ 00:35:13    ┆             ┆             ┆             ┆             ┆             │
│ 2025-01-01   ┆ 2025-01-01  ┆ 141         ┆ 0.6         ┆ 1           ┆ 5.1         ┆ 12.1        │
│ 00:44:04     ┆ 00:46:01    ┆             ┆             ┆             ┆             ┆             │
│ 2025-01-01   ┆ 2025-01-01  ┆ 244         ┆ 0.52        ┆ 3           ┆ 7.2         ┆ 9.7         │
│ 00:14:27     ┆ 00:20:01    ┆             ┆             ┆             ┆             ┆             │
│ 2025-01-01   ┆ 2025-01-01  ┆ 244         ┆ 0.66        ┆ 3           ┆ 5.8         ┆ 8.3         │
│ 00:21:34     ┆ 00:25:06    ┆             ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [38]:
df.describe()

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ pickup_dt  ┆ dropoff_dt ┆ PULocatio ┆ trip_dist ┆ passenger ┆ fare_amou ┆ total_amo │
│ ---        ┆ ---        ┆ ---        ┆ nID       ┆ ance      ┆ _count    ┆ nt        ┆ unt       │
│ str        ┆ str        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 3475226    ┆ 3475226    ┆ 3.475226e ┆ 3.475226e ┆ 2.935077e ┆ 3.475226e ┆ 3.475226e │
│            ┆            ┆            ┆ 6         ┆ 6         ┆ 6         ┆ 6         ┆ 6         │
│ null_count ┆ 0          ┆ 0          ┆ 0.0       ┆ 0.0       ┆ 540149.0  ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 2025-01-17 ┆ 2025-01-17 ┆ 165.19157 ┆ 5.855126  ┆ 1.297859  ┆ 17.081803 ┆ 25.611292 │
│            ┆ 11:02:55.9 ┆ 11:17:56.9 ┆ 6         ┆           ┆           ┆           ┆           │
│            ┆ 10964      ┆ 97901      ┆           ┆           ┆           ┆           ┆           │
│ std        ┆ null       ┆ null       ┆ 64.529483 ┆ 564.6016  ┆ 0.75075   ┆ 463.47291 ┆ 463.65847 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 8         ┆ 8         │
│ min        ┆ 2024-12-31 ┆ 2024-12-18 ┆ 1.0       ┆ 0.0       ┆ 0.0       ┆ -900.0    ┆ -901.0    │
│            ┆ 20:47:55   ┆ 07:52:40   ┆           ┆           ┆           ┆           ┆           │
│ 25%        ┆ 2025-01-10 ┆ 2025-01-10 ┆ 132.0     ┆ 0.98      ┆ 1.0       ┆ 8.6       ┆ 15.2      │
│            ┆ 07:59:01   ┆ 08:15:29   ┆           ┆           ┆           ┆           ┆           │
│ 50%        ┆ 2025-01-17 ┆ 2025-01-17 ┆ 162.0     ┆ 1.67      ┆ 1.0       ┆ 12.11     ┆ 19.95     │
│            ┆ 15:41:34   ┆ 15:59:34   ┆           ┆           ┆           ┆           ┆           │
│ 75%        ┆ 2025-01-24 ┆ 2025-01-24 ┆ 234.0     ┆ 3.1       ┆ 1.0       ┆ 19.5      ┆ 27.78     │
│            ┆ 19:34:06   ┆ 19:48:31   ┆           ┆           ┆           ┆           ┆           │
│ max        ┆ 2025-02-01 ┆ 2025-02-01 ┆ 265.0     ┆ 276423.57 ┆ 9.0       ┆ 863372.12 ┆ 863380.37 │
│            ┆ 00:00:44   ┆ 23:44:11   ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [39]:
df=df.drop_nulls(subset=['pickup_dt'])

In [40]:
df.shape

(3475226, 7)

In [41]:
df=df.filter(
    (pl.col("trip_distance")>0) &
    (pl.col("fare_amount")>0 ) &
    (pl.col("PULocationID").is_between(1,263)) &
    (pl.col("pickup_dt").dt.year()==2025)
)

In [42]:
df.shape

(3245616, 7)

In [43]:
df=df.with_columns(
    pl.col("pickup_dt")
    .dt.truncate("1h")
    .alias("pickup_hour")
)

In [44]:
agg_df=df.group_by(["pickup_hour","PULocationID"]).len().rename({"len":"trip_count"})

In [45]:
agg_df[13500:135510]

shape: (77_595, 3)
┌─────────────────────┬──────────────┬────────────┐
│ pickup_hour         ┆ PULocationID ┆ trip_count │
│ ---                 ┆ ---          ┆ ---        │
│ datetime[μs]        ┆ i32          ┆ u32        │
╞═════════════════════╪══════════════╪════════════╡
│ 2025-01-14 22:00:00 ┆ 256          ┆ 2          │
│ 2025-01-29 17:00:00 ┆ 10           ┆ 1          │
│ 2025-01-19 13:00:00 ┆ 186          ┆ 277        │
│ 2025-01-29 12:00:00 ┆ 54           ┆ 1          │
│ 2025-01-05 06:00:00 ┆ 170          ┆ 8          │
│ …                   ┆ …            ┆ …          │
│ 2025-01-31 07:00:00 ┆ 232          ┆ 10         │
│ 2025-01-06 14:00:00 ┆ 53           ┆ 1          │
│ 2025-01-28 05:00:00 ┆ 20           ┆ 2          │
│ 2025-01-15 12:00:00 ┆ 51           ┆ 3          │
│ 2025-01-30 23:00:00 ┆ 193          ┆ 1          │
└─────────────────────┴──────────────┴────────────┘

In [63]:
agg_df.sort(['pickup_hour']).tail()

shape: (5, 3)
┌─────────────────────┬──────────────┬────────────┐
│ pickup_hour         ┆ PULocationID ┆ trip_count │
│ ---                 ┆ ---          ┆ ---        │
│ datetime[μs]        ┆ i32          ┆ u32        │
╞═════════════════════╪══════════════╪════════════╡
│ 2025-01-31 23:00:00 ┆ 65           ┆ 15         │
│ 2025-01-31 23:00:00 ┆ 45           ┆ 43         │
│ 2025-01-31 23:00:00 ┆ 186          ┆ 113        │
│ 2025-01-31 23:00:00 ┆ 215          ┆ 1          │
│ 2025-02-01 00:00:00 ┆ 113          ┆ 1          │
└─────────────────────┴──────────────┴────────────┘

In [46]:
agg_df.shape

(91095, 3)

In [47]:
all_hours=pl.datetime_range(
    start=df['pickup_dt'].min().replace(minute=0,second=0,microsecond=0),
    end=df['pickup_dt'].max().replace(minute=0,second=0,microsecond=0),
    interval='1h',
    eager=True
).alias("pickup_hour")

In [48]:
all_hours

shape: (745,)
Series: 'pickup_hour' [datetime[μs]]
[
	2025-01-01 00:00:00
	2025-01-01 01:00:00
	2025-01-01 02:00:00
	2025-01-01 03:00:00
	2025-01-01 04:00:00
	…
	2025-01-31 20:00:00
	2025-01-31 21:00:00
	2025-01-31 22:00:00
	2025-01-31 23:00:00
	2025-02-01 00:00:00
]

In [49]:
all_zones=pl.Series("PULocationID",list(range(1,264)))

In [50]:
all_zones

shape: (263,)
Series: 'PULocationID' [i64]
[
	1
	2
	3
	4
	5
	…
	259
	260
	261
	262
	263
]

In [52]:
type(all_hours)

polars.series.series.Series

In [57]:
all_hours.shape

(745,)

In [53]:
type(all_hours.to_frame())

polars.dataframe.frame.DataFrame

In [55]:
full_grid=all_hours.to_frame().join(all_zones.to_frame(),how='cross')

In [56]:
full_grid.shape

(195935, 2)

In [59]:
result=(
    full_grid
    .join(agg_df,on=['pickup_hour',"PULocationID"],how='left')
    .with_columns(pl.col("trip_count").fill_null(0))
    .sort(['pickup_hour',"PULocationID"])
)

In [76]:
def add_time_features(df:pl.DataFrame)->pl.DataFrame:
    time_df=df.with_columns(
        [
            pl.col("pickup_hour")
            .dt.hour()
            .alias("hour_of_day"),

           pl.col("pickup_hour")
            .dt.weekday()
            .alias("day_of_week"),

            pl.col("pickup_hour")
            .dt.month()
            .alias("month"),

            (pl.col("pickup_hour").dt.weekday()>=5)
            .alias("is_weekend"),

            pl.col("pickup_hour")
            .dt.hour()
            .is_in([7,8,9,17,18,19])
            .alias("is_rush_hour"),
        ]
    )
    return time_df

In [77]:
def add_lag_features(df:pl.DataFrame)->pl.DataFrame:
    lag_df=df.with_columns(
        [
            pl.col("trip_count")
            .shift(1)
            .over("PULocationID")
            .alias("lag_1h"),

            pl.col("trip_count")
            .shift(24)
            .over("PULocationID")
            .alias("lag_24h"),

            pl.col("trip_count")
            .shift(168)
            .over("PULocationID")
            .alias("lag_168h"),
        ]
    )
    return lag_df

In [78]:
def add_rolling_features(df:pl.DataFrame)->pl.DataFrame:
    rolling_df=df.with_columns(
        [
            pl.col("trip_count")
            .shift(1)
            .rolling_mean(window_size=3)
            .over("PULocationID")
            .alias("rolling_mean_3h"),

            pl.col("trip_count")
            .shift(1)
            .rolling_mean(window_size=24)
            .over("PULocationID")
            .alias("rolling_mean_24h")
        ]
    )
    return rolling_df

In [79]:

def drop_nulls(df:pl.DataFrame)->pl.DataFrame:
    df=df.drop_nulls(subset=[
        'lag_1h',
        'lag_24h',
        'lag_168h',
        'rolling_mean_3h',
        'rolling_mean_24h'
        ])
    return df

In [80]:
TARGET_COL = "trip_count"
LOCATION_COL = "PULocationID"
TIME_COL = "pickup_hour"

In [81]:
def build_features(df:pl.DataFrame)->pl.DataFrame:
    df=df.sort([LOCATION_COL,TIME_COL])
    df=add_time_features(df)
    df=add_lag_features(df)
    df=add_rolling_features(df)
    df=drop_nulls(df)
    return df

In [82]:
featured_df=build_features(result)

In [83]:
featured_df

shape: (151_751, 13)
┌────────────┬────────────┬───────────┬───────────┬───┬─────────┬──────────┬───────────┬───────────┐
│ pickup_hou ┆ PULocation ┆ trip_coun ┆ hour_of_d ┆ … ┆ lag_24h ┆ lag_168h ┆ rolling_m ┆ rolling_m │
│ r          ┆ ID         ┆ t         ┆ ay        ┆   ┆ ---     ┆ ---      ┆ ean_3h    ┆ ean_24h   │
│ ---        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ u32     ┆ u32      ┆ ---       ┆ ---       │
│ datetime[μ ┆ i64        ┆ u32       ┆ i8        ┆   ┆         ┆          ┆ f64       ┆ f64       │
│ s]         ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═════════╪══════════╪═══════════╪═══════════╡
│ 2025-01-08 ┆ 1          ┆ 0         ┆ 0         ┆ … ┆ 0       ┆ 0        ┆ 0.0       ┆ 0.083333  │
│ 00:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ 2025-01-08 ┆ 1          ┆ 0         ┆ 1         ┆ … ┆ 0       ┆ 0        ┆ 0.0       ┆ 0.083333  │
│ 01:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ 2025-01-08 ┆ 1          ┆ 0         ┆ 2         ┆ … ┆ 0       ┆ 0        ┆ 0.0       ┆ 0.083333  │
│ 02:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ 2025-01-08 ┆ 1          ┆ 0         ┆ 3         ┆ … ┆ 0       ┆ 0        ┆ 0.0       ┆ 0.083333  │
│ 03:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ 2025-01-08 ┆ 1          ┆ 0         ┆ 4         ┆ … ┆ 0       ┆ 0        ┆ 0.0       ┆ 0.083333  │
│ 04:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …       ┆ …        ┆ …         ┆ …         │
│ 2025-01-31 ┆ 263        ┆ 131       ┆ 20        ┆ … ┆ 123     ┆ 151      ┆ 196.33333 ┆ 99.541667 │
│ 20:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆ 3         ┆           │
│ 2025-01-31 ┆ 263        ┆ 128       ┆ 21        ┆ … ┆ 106     ┆ 133      ┆ 180.0     ┆ 99.875    │
│ 21:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ 2025-01-31 ┆ 263        ┆ 162       ┆ 22        ┆ … ┆ 81      ┆ 106      ┆ 147.0     ┆ 100.79166 │
│ 22:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆ 7         │
│ 2025-01-31 ┆ 263        ┆ 121       ┆ 23        ┆ … ┆ 46      ┆ 128      ┆ 140.33333 ┆ 104.16666 │
│ 23:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆ 3         ┆ 7         │
│ 2025-02-01 ┆ 263        ┆ 0         ┆ 0         ┆ … ┆ 22      ┆ 92       ┆ 137.0     ┆ 107.29166 │
│ 00:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆ 7         │
└────────────┴────────────┴───────────┴───────────┴───┴─────────┴──────────┴───────────┴───────────┘

In [85]:
featured_df.filter(
    pl.col("PULocationID") == 1
)

shape: (577, 13)
┌────────────┬────────────┬───────────┬───────────┬───┬─────────┬──────────┬───────────┬───────────┐
│ pickup_hou ┆ PULocation ┆ trip_coun ┆ hour_of_d ┆ … ┆ lag_24h ┆ lag_168h ┆ rolling_m ┆ rolling_m │
│ r          ┆ ID         ┆ t         ┆ ay        ┆   ┆ ---     ┆ ---      ┆ ean_3h    ┆ ean_24h   │
│ ---        ┆ ---        ┆ ---       ┆ ---       ┆   ┆ u32     ┆ u32      ┆ ---       ┆ ---       │
│ datetime[μ ┆ i64        ┆ u32       ┆ i8        ┆   ┆         ┆          ┆ f64       ┆ f64       │
│ s]         ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═════════╪══════════╪═══════════╪═══════════╡
│ 2025-01-08 ┆ 1          ┆ 0         ┆ 0         ┆ … ┆ 0       ┆ 0        ┆ 0.0       ┆ 0.083333  │
│ 00:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ 2025-01-08 ┆ 1          ┆ 0         ┆ 1         ┆ … ┆ 0       ┆ 0        ┆ 0.0       ┆ 0.083333  │
│ 01:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ 2025-01-08 ┆ 1          ┆ 0         ┆ 2         ┆ … ┆ 0       ┆ 0        ┆ 0.0       ┆ 0.083333  │
│ 02:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ 2025-01-08 ┆ 1          ┆ 0         ┆ 3         ┆ … ┆ 0       ┆ 0        ┆ 0.0       ┆ 0.083333  │
│ 03:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ 2025-01-08 ┆ 1          ┆ 0         ┆ 4         ┆ … ┆ 0       ┆ 0        ┆ 0.0       ┆ 0.083333  │
│ 04:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …       ┆ …        ┆ …         ┆ …         │
│ 2025-01-31 ┆ 1          ┆ 0         ┆ 20        ┆ … ┆ 0       ┆ 0        ┆ 0.0       ┆ 0.0       │
│ 20:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ 2025-01-31 ┆ 1          ┆ 0         ┆ 21        ┆ … ┆ 0       ┆ 0        ┆ 0.0       ┆ 0.0       │
│ 21:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ 2025-01-31 ┆ 1          ┆ 0         ┆ 22        ┆ … ┆ 0       ┆ 0        ┆ 0.0       ┆ 0.0       │
│ 22:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ 2025-01-31 ┆ 1          ┆ 0         ┆ 23        ┆ … ┆ 0       ┆ 0        ┆ 0.0       ┆ 0.0       │
│ 23:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
│ 2025-02-01 ┆ 1          ┆ 0         ┆ 0         ┆ … ┆ 0       ┆ 0        ┆ 0.0       ┆ 0.0       │
│ 00:00:00   ┆            ┆           ┆           ┆   ┆         ┆          ┆           ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴─────────┴──────────┴───────────┴───────────┘

In [88]:
from pathlib import Path

In [92]:
df = result.sort(["PULocationID", "pickup_hour"])

zone1 = df.filter(pl.col("PULocationID") == 1)
print(zone1.head(30))
print("trip_count values:", zone1["trip_count"].head(30).to_list())

shape: (30, 3)
┌─────────────────────┬──────────────┬────────────┐
│ pickup_hour         ┆ PULocationID ┆ trip_count │
│ ---                 ┆ ---          ┆ ---        │
│ datetime[μs]        ┆ i64          ┆ u32        │
╞═════════════════════╪══════════════╪════════════╡
│ 2025-01-01 00:00:00 ┆ 1            ┆ 0          │
│ 2025-01-01 01:00:00 ┆ 1            ┆ 0          │
│ 2025-01-01 02:00:00 ┆ 1            ┆ 0          │
│ 2025-01-01 03:00:00 ┆ 1            ┆ 0          │
│ 2025-01-01 04:00:00 ┆ 1            ┆ 0          │
│ …                   ┆ …            ┆ …          │
│ 2025-01-02 01:00:00 ┆ 1            ┆ 0          │
│ 2025-01-02 02:00:00 ┆ 1            ┆ 0          │
│ 2025-01-02 03:00:00 ┆ 1            ┆ 0          │
│ 2025-01-02 04:00:00 ┆ 1            ┆ 0          │
│ 2025-01-02 05:00:00 ┆ 1            ┆ 0          │
└─────────────────────┴──────────────┴────────────┘
trip_count values: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [93]:
zone1 = df.filter(pl.col("PULocationID") == 1)
print("total zone 1 rows:", len(zone1))
print("zero trip_count rows:", len(zone1.filter(pl.col("trip_count") == 0)))
print("non-zero trip_count rows:", len(zone1.filter(pl.col("trip_count") > 0)))
print(zone1.head(10))

total zone 1 rows: 745
zero trip_count rows: 682
non-zero trip_count rows: 63
shape: (10, 3)
┌─────────────────────┬──────────────┬────────────┐
│ pickup_hour         ┆ PULocationID ┆ trip_count │
│ ---                 ┆ ---          ┆ ---        │
│ datetime[μs]        ┆ i64          ┆ u32        │
╞═════════════════════╪══════════════╪════════════╡
│ 2025-01-01 00:00:00 ┆ 1            ┆ 0          │
│ 2025-01-01 01:00:00 ┆ 1            ┆ 0          │
│ 2025-01-01 02:00:00 ┆ 1            ┆ 0          │
│ 2025-01-01 03:00:00 ┆ 1            ┆ 0          │
│ 2025-01-01 04:00:00 ┆ 1            ┆ 0          │
│ 2025-01-01 05:00:00 ┆ 1            ┆ 0          │
│ 2025-01-01 06:00:00 ┆ 1            ┆ 1          │
│ 2025-01-01 07:00:00 ┆ 1            ┆ 0          │
│ 2025-01-01 08:00:00 ┆ 1            ┆ 0          │
│ 2025-01-01 09:00:00 ┆ 1            ┆ 0          │
└─────────────────────┴──────────────┴────────────┘

In [94]:
print("zone 1 total rows:", len(zone1))

# manually compute what rolling_mean_24h should be for first 30 rows
trip_counts = zone1["trip_count"].head(30).to_list()
print("raw trip_counts:", trip_counts)

# shift by 1 then rolling mean of 24
shifted = [None] + trip_counts[:-1]
print("shifted:", shifted[:30])

# rolling mean of 24 on shifted
for i in range(30):
    window = shifted[max(0,i-23):i+1]
    valid = [x for x in window if x is not None]
    mean = sum(valid)/len(valid) if valid else None
    print(f"row {i}: window_size={len(valid)}, mean={mean}")

zone 1 total rows: 745
raw trip_counts: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
shifted: [None, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
row 0: window_size=0, mean=None
row 1: window_size=1, mean=0.0
row 2: window_size=2, mean=0.0
row 3: window_size=3, mean=0.0
row 4: window_size=4, mean=0.0
row 5: window_size=5, mean=0.0
row 6: window_size=6, mean=0.0
row 7: window_size=7, mean=0.14285714285714285
row 8: window_size=8, mean=0.125
row 9: window_size=9, mean=0.1111111111111111
row 10: window_size=10, mean=0.1
row 11: window_size=11, mean=0.09090909090909091
row 12: window_size=12, mean=0.08333333333333333
row 13: window_size=13, mean=0.07692307692307693
row 14: window_size=14, mean=0.14285714285714285
row 15: window_size=15, mean=0.2
row 16: window_size=16, mean=0.1875
row 17: window_size=17, mean=0.23529411764705882
row 18: window_size=18, mean=0.2222222222222222
row 19: window_size=19, mean=0.2631578947368421
row 20: window_size=20, mean=0.25
row 21: window_size=21, mean=0.23809523809523808
row 22: window_size=22, mean=0.22727272727272727
row 23: window_size=23, mean=0.21739130434782608
row 24: window_size=24, mean=0.20833333333333334
row 25: window_size=24, mean=0.20833333333333334
row 26: window_size=24, mean=0.20833333333333334
row 27: window_size=24, mean=0.20833333333333334
row 28: window_size=24, mean=0.20833333333333334
row 29: window_size=24, mean=0.20833333333333334