In [2]:
import polars as pl

In [ ]:
import polars as pl

df = pl.read_parquet(
    "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-01.parquet"
)
df.describe()

OSError: object-store error: The operation lacked the necessary privileges to complete for path : Error performing HEAD https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-01.parquet in 69.6097ms - Server returned non-2xx status code: 403 Forbidden:  (path: https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-01.parquet)

In [3]:
df.shape

(3475226, 20)

In [12]:
import pandas as pd

df = pd.read_parquet(
    "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-01.parquet"
)
print(df.info())
print(df.head(3))
print(df.isnull().sum())

HTTPError: HTTP Error 403: Forbidden

In [15]:
import requests
from pathlib import Path

download_dir = Path("../data/raw")
download_dir.mkdir(exist_ok=True)

for month in range(1, 13):
    url = f"https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2025-{month:02d}.parquet"
    file_path = download_dir / f"yellow_tripdata_2025-{month:02d}.parquet"

    try:
        print(f"Downloading {month:02d}...")
        response = requests.get(url, stream=True, timeout=60)
        response.raise_for_status()

        with open(file_path, "wb") as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)

        print(f"✓ Saved {file_path}")

    except Exception as e:
        print(f"✗ Failed month {month:02d}: {e}")

Downloading 01...
✓ Saved ..\data\raw\yellow_tripdata_2025-01.parquet
Downloading 02...
✓ Saved ..\data\raw\yellow_tripdata_2025-02.parquet
Downloading 03...
✓ Saved ..\data\raw\yellow_tripdata_2025-03.parquet
Downloading 04...
✓ Saved ..\data\raw\yellow_tripdata_2025-04.parquet
Downloading 05...
✓ Saved ..\data\raw\yellow_tripdata_2025-05.parquet
Downloading 06...
✓ Saved ..\data\raw\yellow_tripdata_2025-06.parquet
Downloading 07...
✓ Saved ..\data\raw\yellow_tripdata_2025-07.parquet
Downloading 08...
✓ Saved ..\data\raw\yellow_tripdata_2025-08.parquet
Downloading 09...
✓ Saved ..\data\raw\yellow_tripdata_2025-09.parquet
Downloading 10...
✓ Saved ..\data\raw\yellow_tripdata_2025-10.parquet
Downloading 11...
✓ Saved ..\data\raw\yellow_tripdata_2025-11.parquet
Downloading 12...
✓ Saved ..\data\raw\yellow_tripdata_2025-12.parquet

In [24]:
COLUMNS_TO_KEEP = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime",
    "PULocationID",
    "trip_distance",
    "passenger_count",
    "fare_amount",
    "total_amount",
]

In [25]:
df=pl.read_parquet("../data/raw/yellow_tripdata_2025-01.parquet",columns=COLUMNS_TO_KEEP)

In [26]:
df.head()

shape: (5, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ tpep_pickup_ ┆ tpep_dropof ┆ PULocationI ┆ trip_distan ┆ passenger_c ┆ fare_amount ┆ total_amoun │
│ datetime     ┆ f_datetime  ┆ D           ┆ ce          ┆ ount        ┆ ---         ┆ t           │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ f64         ┆ ---         │
│ datetime[μs] ┆ datetime[μs ┆ i32         ┆ f64         ┆ i64         ┆             ┆ f64         │
│              ┆ ]           ┆             ┆             ┆             ┆             ┆             │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 2025-01-01   ┆ 2025-01-01  ┆ 229         ┆ 1.6         ┆ 1           ┆ 10.0        ┆ 18.0        │
│ 00:18:38     ┆ 00:26:59    ┆             ┆             ┆             ┆             ┆             │
│ 2025-01-01   ┆ 2025-01-01  ┆ 236         ┆ 0.5         ┆ 1           ┆ 5.1         ┆ 12.12       │
│ 00:32:40     ┆ 00:35:13    ┆             ┆             ┆             ┆             ┆             │
│ 2025-01-01   ┆ 2025-01-01  ┆ 141         ┆ 0.6         ┆ 1           ┆ 5.1         ┆ 12.1        │
│ 00:44:04     ┆ 00:46:01    ┆             ┆             ┆             ┆             ┆             │
│ 2025-01-01   ┆ 2025-01-01  ┆ 244         ┆ 0.52        ┆ 3           ┆ 7.2         ┆ 9.7         │
│ 00:14:27     ┆ 00:20:01    ┆             ┆             ┆             ┆             ┆             │
│ 2025-01-01   ┆ 2025-01-01  ┆ 244         ┆ 0.66        ┆ 3           ┆ 5.8         ┆ 8.3         │
│ 00:21:34     ┆ 00:25:06    ┆             ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [27]:
df=df.rename({"tpep_pickup_datetime":"pickup_dt","tpep_dropoff_datetime":"dropoff_dt"})

In [29]:
df.head()

shape: (5, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ pickup_dt    ┆ dropoff_dt  ┆ PULocationI ┆ trip_distan ┆ passenger_c ┆ fare_amount ┆ total_amoun │
│ ---          ┆ ---         ┆ D           ┆ ce          ┆ ount        ┆ ---         ┆ t           │
│ datetime[μs] ┆ datetime[μs ┆ ---         ┆ ---         ┆ ---         ┆ f64         ┆ ---         │
│              ┆ ]           ┆ i32         ┆ f64         ┆ i64         ┆             ┆ f64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 2025-01-01   ┆ 2025-01-01  ┆ 229         ┆ 1.6         ┆ 1           ┆ 10.0        ┆ 18.0        │
│ 00:18:38     ┆ 00:26:59    ┆             ┆             ┆             ┆             ┆             │
│ 2025-01-01   ┆ 2025-01-01  ┆ 236         ┆ 0.5         ┆ 1           ┆ 5.1         ┆ 12.12       │
│ 00:32:40     ┆ 00:35:13    ┆             ┆             ┆             ┆             ┆             │
│ 2025-01-01   ┆ 2025-01-01  ┆ 141         ┆ 0.6         ┆ 1           ┆ 5.1         ┆ 12.1        │
│ 00:44:04     ┆ 00:46:01    ┆             ┆             ┆             ┆             ┆             │
│ 2025-01-01   ┆ 2025-01-01  ┆ 244         ┆ 0.52        ┆ 3           ┆ 7.2         ┆ 9.7         │
│ 00:14:27     ┆ 00:20:01    ┆             ┆             ┆             ┆             ┆             │
│ 2025-01-01   ┆ 2025-01-01  ┆ 244         ┆ 0.66        ┆ 3           ┆ 5.8         ┆ 8.3         │
│ 00:21:34     ┆ 00:25:06    ┆             ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [ ]:
df.describe()

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ pickup_dt  ┆ dropoff_dt ┆ PULocatio ┆ trip_dist ┆ passenger ┆ fare_amou ┆ total_amo │
│ ---        ┆ ---        ┆ ---        ┆ nID       ┆ ance      ┆ _count    ┆ nt        ┆ unt       │
│ str        ┆ str        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 3475226    ┆ 3475226    ┆ 3.475226e ┆ 3.475226e ┆ 2.935077e ┆ 3.475226e ┆ 3.475226e │
│            ┆            ┆            ┆ 6         ┆ 6         ┆ 6         ┆ 6         ┆ 6         │
│ null_count ┆ 0          ┆ 0          ┆ 0.0       ┆ 0.0       ┆ 540149.0  ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 2025-01-17 ┆ 2025-01-17 ┆ 165.19157 ┆ 5.855126  ┆ 1.297859  ┆ 17.081803 ┆ 25.611292 │
│            ┆ 11:02:55.9 ┆ 11:17:56.9 ┆ 6         ┆           ┆           ┆           ┆           │
│            ┆ 10964      ┆ 97901      ┆           ┆           ┆           ┆           ┆           │
│ std        ┆ null       ┆ null       ┆ 64.529483 ┆ 564.6016  ┆ 0.75075   ┆ 463.47291 ┆ 463.65847 │
│            ┆            ┆            ┆           ┆           ┆           ┆ 8         ┆ 8         │
│ min        ┆ 2024-12-31 ┆ 2024-12-18 ┆ 1.0       ┆ 0.0       ┆ 0.0       ┆ -900.0    ┆ -901.0    │
│            ┆ 20:47:55   ┆ 07:52:40   ┆           ┆           ┆           ┆           ┆           │
│ 25%        ┆ 2025-01-10 ┆ 2025-01-10 ┆ 132.0     ┆ 0.98      ┆ 1.0       ┆ 8.6       ┆ 15.2      │
│            ┆ 07:59:01   ┆ 08:15:29   ┆           ┆           ┆           ┆           ┆           │
│ 50%        ┆ 2025-01-17 ┆ 2025-01-17 ┆ 162.0     ┆ 1.67      ┆ 1.0       ┆ 12.11     ┆ 19.95     │
│            ┆ 15:41:34   ┆ 15:59:34   ┆           ┆           ┆           ┆           ┆           │
│ 75%        ┆ 2025-01-24 ┆ 2025-01-24 ┆ 234.0     ┆ 3.1       ┆ 1.0       ┆ 19.5      ┆ 27.78     │
│            ┆ 19:34:06   ┆ 19:48:31   ┆           ┆           ┆           ┆           ┆           │
│ max        ┆ 2025-02-01 ┆ 2025-02-01 ┆ 265.0     ┆ 276423.57 ┆ 9.0       ┆ 863372.12 ┆ 863380.37 │
│            ┆ 00:00:44   ┆ 23:44:11   ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [31]:
df=df.drop_nulls(subset=['pickup_dt'])

In [32]:
df.shape

(3475226, 7)

In [33]:
df=df.filter(
    (pl.col("trip_distance")>0) &
    (pl.col("fare_amount")>0 ) &
    (pl.col("PULocationID").is_between(1,263)) &
    (pl.col("pickup_dt").dt.year()==2025)
)

In [34]:
df.shape

(3245616, 7)

In [35]:
df=df.with_columns(
    pl.col("pickup_dt")
    .dt.truncate("1h")
    .alias("pickup_hour")
)

In [47]:
df.group_by(["pickup_hour","PULocationID"]).len().rename({"len":"trip_count"}).sort(["pickup_hour","PULocationID"])

shape: (91_095, 3)
┌─────────────────────┬──────────────┬────────────┐
│ pickup_hour         ┆ PULocationID ┆ trip_count │
│ ---                 ┆ ---          ┆ ---        │
│ datetime[μs]        ┆ i32          ┆ u32        │
╞═════════════════════╪══════════════╪════════════╡
│ 2025-01-01 00:00:00 ┆ 4            ┆ 26         │
│ 2025-01-01 00:00:00 ┆ 7            ┆ 6          │
│ 2025-01-01 00:00:00 ┆ 9            ┆ 1          │
│ 2025-01-01 00:00:00 ┆ 10           ┆ 1          │
│ 2025-01-01 00:00:00 ┆ 12           ┆ 1          │
│ …                   ┆ …            ┆ …          │
│ 2025-01-31 23:00:00 ┆ 260          ┆ 3          │
│ 2025-01-31 23:00:00 ┆ 261          ┆ 33         │
│ 2025-01-31 23:00:00 ┆ 262          ┆ 28         │
│ 2025-01-31 23:00:00 ┆ 263          ┆ 121        │
│ 2025-02-01 00:00:00 ┆ 113          ┆ 1          │
└─────────────────────┴──────────────┴────────────┘

In [42]:
df[13500:135510]

shape: (122_010, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ pickup_dt  ┆ dropoff_dt ┆ PULocation ┆ trip_dist ┆ passenger ┆ fare_amou ┆ total_amo ┆ pickup_ho │
│ ---        ┆ ---        ┆ ID         ┆ ance      ┆ _count    ┆ nt        ┆ unt       ┆ ur        │
│ datetime[μ ┆ datetime[μ ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆ s]         ┆ i32        ┆ f64       ┆ i64       ┆ f64       ┆ f64       ┆ datetime[ │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ μs]       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2025-01-01 ┆ 2025-01-01 ┆ 107        ┆ 0.9       ┆ 1         ┆ 7.2       ┆ 12.2      ┆ 2025-01-0 │
│ 02:18:50   ┆ 02:23:16   ┆            ┆           ┆           ┆           ┆           ┆ 1         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 02:00:00  │
│ 2025-01-01 ┆ 2025-01-01 ┆ 107        ┆ 6.6       ┆ 1         ┆ 29.6      ┆ 43.25     ┆ 2025-01-0 │
│ 02:34:08   ┆ 02:57:43   ┆            ┆           ┆           ┆           ┆           ┆ 1         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 02:00:00  │
│ 2025-01-01 ┆ 2025-01-01 ┆ 246        ┆ 3.97      ┆ 1         ┆ 30.3      ┆ 42.36     ┆ 2025-01-0 │
│ 02:15:14   ┆ 02:47:03   ┆            ┆           ┆           ┆           ┆           ┆ 1         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 02:00:00  │
│ 2025-01-01 ┆ 2025-01-01 ┆ 234        ┆ 1.66      ┆ 4         ┆ 12.1      ┆ 20.52     ┆ 2025-01-0 │
│ 02:10:19   ┆ 02:21:38   ┆            ┆           ┆           ┆           ┆           ┆ 1         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 02:00:00  │
│ 2025-01-01 ┆ 2025-01-01 ┆ 234        ┆ 12.54     ┆ 4         ┆ 52.7      ┆ 77.57     ┆ 2025-01-0 │
│ 02:37:33   ┆ 03:12:52   ┆            ┆           ┆           ┆           ┆           ┆ 1         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 02:00:00  │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2025-01-02 ┆ 2025-01-02 ┆ 161        ┆ 0.41      ┆ 2         ┆ 9.3       ┆ 16.44     ┆ 2025-01-0 │
│ 20:17:52   ┆ 20:27:30   ┆            ┆           ┆           ┆           ┆           ┆ 2         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 20:00:00  │
│ 2025-01-02 ┆ 2025-01-02 ┆ 234        ┆ 1.1       ┆ 2         ┆ 7.9       ┆ 15.48     ┆ 2025-01-0 │
│ 20:53:34   ┆ 21:00:19   ┆            ┆           ┆           ┆           ┆           ┆ 2         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 20:00:00  │
│ 2025-01-02 ┆ 2025-01-02 ┆ 138        ┆ 12.31     ┆ 1         ┆ 45.7      ┆ 73.92     ┆ 2025-01-0 │
│ 20:58:17   ┆ 21:17:04   ┆            ┆           ┆           ┆           ┆           ┆ 2         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 20:00:00  │
│ 2025-01-02 ┆ 2025-01-02 ┆ 88         ┆ 9.93      ┆ 1         ┆ 42.2      ┆ 47.2      ┆ 2025-01-0 │
│ 20:00:46   ┆ 20:26:00   ┆            ┆           ┆           ┆           ┆           ┆ 2         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 20:00:00  │
│ 2025-01-02 ┆ 2025-01-02 ┆ 229        ┆ 2.0       ┆ 1         ┆ 12.8      ┆ 17.8      ┆ 2025-01-0 │
│ 20:36:37   ┆ 20:47:42   ┆            ┆           ┆           ┆           ┆           ┆ 2         │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ 20:00:00  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [8]:
train_df=pl.read_parquet("../data/processed/train.parquet")
stream_df=pl.read_parquet("../data/processed/stream.parquet")

In [9]:
train_df.head()

shape: (5, 3)
┌─────────────────────┬──────────────┬────────────┐
│ pickup_hour         ┆ PULocationID ┆ trip_count │
│ ---                 ┆ ---          ┆ ---        │
│ datetime[μs]        ┆ i32          ┆ u32        │
╞═════════════════════╪══════════════╪════════════╡
│ 2025-01-01 00:00:00 ┆ 4            ┆ 26         │
│ 2025-01-01 00:00:00 ┆ 7            ┆ 6          │
│ 2025-01-01 00:00:00 ┆ 9            ┆ 1          │
│ 2025-01-01 00:00:00 ┆ 10           ┆ 1          │
│ 2025-01-01 00:00:00 ┆ 12           ┆ 1          │
└─────────────────────┴──────────────┴────────────┘

In [10]:
train_df.tail()

shape: (5, 3)
┌─────────────────────┬──────────────┬────────────┐
│ pickup_hour         ┆ PULocationID ┆ trip_count │
│ ---                 ┆ ---          ┆ ---        │
│ datetime[μs]        ┆ i32          ┆ u32        │
╞═════════════════════╪══════════════╪════════════╡
│ 2025-06-30 23:00:00 ┆ 257          ┆ 2          │
│ 2025-06-30 23:00:00 ┆ 258          ┆ 2          │
│ 2025-06-30 23:00:00 ┆ 261          ┆ 10         │
│ 2025-06-30 23:00:00 ┆ 262          ┆ 15         │
│ 2025-06-30 23:00:00 ┆ 263          ┆ 32         │
└─────────────────────┴──────────────┴────────────┘

In [11]:
stream_df.head()

shape: (5, 3)
┌─────────────────────┬──────────────┬────────────┐
│ pickup_hour         ┆ PULocationID ┆ trip_count │
│ ---                 ┆ ---          ┆ ---        │
│ datetime[μs]        ┆ i32          ┆ u32        │
╞═════════════════════╪══════════════╪════════════╡
│ 2025-07-01 00:00:00 ┆ 3            ┆ 1          │
│ 2025-07-01 00:00:00 ┆ 4            ┆ 9          │
│ 2025-07-01 00:00:00 ┆ 7            ┆ 9          │
│ 2025-07-01 00:00:00 ┆ 10           ┆ 5          │
│ 2025-07-01 00:00:00 ┆ 13           ┆ 12         │
└─────────────────────┴──────────────┴────────────┘

In [12]:
stream_df.tail()

shape: (5, 3)
┌─────────────────────┬──────────────┬────────────┐
│ pickup_hour         ┆ PULocationID ┆ trip_count │
│ ---                 ┆ ---          ┆ ---        │
│ datetime[μs]        ┆ i32          ┆ u32        │
╞═════════════════════╪══════════════╪════════════╡
│ 2025-12-31 23:00:00 ┆ 259          ┆ 1          │
│ 2025-12-31 23:00:00 ┆ 260          ┆ 6          │
│ 2025-12-31 23:00:00 ┆ 261          ┆ 24         │
│ 2025-12-31 23:00:00 ┆ 262          ┆ 68         │
│ 2025-12-31 23:00:00 ┆ 263          ┆ 153        │
└─────────────────────┴──────────────┴────────────┘